sonar.projectKey=api-crud-produits
sonar.projectName=API CRUD Produits
sonar.projectVersion=1.0

sonar.sources=app
sonar.tests=tests
sonar.language=py
sonar.sourceEncoding=UTF-8

sonar.python.coverage.reportPaths=coverage.xml
sonar.python.version=3

sonar.exclusions=**/venv/**,**/__pycache__/**,**/*.pyc,**/*.egg-info/**
